---

- name: web servers
  hosts: web
#  become: true
  tasks:
    - name: install Apache, Git
      yum:
        name: httpd,git
        state: present
        update_cache: true

    - name: install packages
      yum:
        name: php
        state: present
        update_cache: true
      notify: restart apache

    - name: start Apache service
      service:
        name: httpd
        state: started
        enabled: yes

    - name: deploy index.php
      git:
        repo: "{{ repository }}"
        dest: "{{ document_root_path }}"

    - name: vhost config block
      block:
      - name: copy vhost config
        copy:
          src: files/ansible_site.conf
          dest: "{{ vhost_config_file }}"
          owner: root
          group: root
          mode: 0644
        notify: restart apache
      - name: check config
        command: httpd -t
      rescue:
      - name: remove bad vhost conf file
        file:
          path: "{{ vhost_config_file }}"
          state: absent
      - name: rolling back - ending playbook
        fail:
          msg: "Conf file is not valid. Please check that before re-running the playbook"

    - name: configure.httpd.conf
      lineinfile:
        path: "{{ apache_config_file }}"
        regexp: "^IncludeOptional"
        line: "IncludeOptional conf.d/*.conf"
      notify: restart apache

  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted

...
